### ISSUE TITLE
Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.

### ISSUE THREAD

**Issue by kfiroo** [apolkingg8/React-Native-Touchable-Ripple#4]
in TouchableRipple.getInitialState we set ripple: {}
when used in a list / repeater React throws this error:
"Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child."

TL;DR
change TouchableRipple.getInitialState to the following will fix it
```javascript
    getInitialState: function getInitialState() {
        return {
            ripple: null
        };
    },
```

**Comment by apolkingg8** [comment]
Sorry for late, thanks for this fix! :beers:
